version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker_image"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/docker_image"
    schedule:
      interval: "weekly"
    groups:
      go-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"