name: Post Pull Request Cleanup
on:
  pull_request:
    types: [ 'closed' ]

jobs:
  cleanup:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest
    environment:
      name: tfauto
    steps:
      - name: Azure login
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 #v2.2.0
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: Delete tfplan file
        run: |
          echo "========> github.event.pull_request.merged is:"
          echo ${{github.event.pull_request.merged}}
          az storage blob delete --account-name tfmod1espoolstatestorage --container-name azure-verified-tfmod-pull-request-plans --name telemetry/tfplan_${{ github.event.number }} --auth-mode login || echo "tfplan file cleanup error but we tolerate it."
          az storage blob delete --account-name tfmod1espoolstatestorage --container-name azure-verified-tfmod-pull-request-plans --name telemetry/tfplan_${{ github.event.number }}.txt --auth-mode login || echo "tfplan file cleanup error but we tolerate it."
