name: PrCheck
on:
  pull_request:
    types: [ 'opened', 'synchronize', 'reopened']
    paths:
      - '.github/**'
      - '**.tf'
      - '**.tf.json'
      - '.github/workflows/**'
      - '**.hcl'
      - '**.go'
      - '**/Dockerfile'

env:
  GITHUB_RUN_ATTEMPT: 3

jobs:
  prepr-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # 2.0.3
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # 4.1.0
        with:
          go-version-file: 'docker_image/go.mod'
      - name: Go test
        run: |
          cd docker_image
          go mod tidy
          go test -v ./...
      - name: Gosec
        run: |
          docker run --rm -v docker_image:/src -w /src securego/gosec:2.17.0 telemetry
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # 3.7.0
        with:
          version: v1.54.2
          working-directory: docker_image
      - name: Docker build test
        run: |
          cd docker_image
          docker build -t test .
