name: Terraform Plan
on:
  pull_request:
    types: [ 'opened', 'synchronize', 'reopened']
    paths:
      - '.github/**'
      - '**.tf'
      - '**.tf.json'
      - '.github/workflows/**'
      - '**.hcl'
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - '**/Dockerfile'
permissions:
  contents: write
  id-token: write

jobs:
  tfplan:
    runs-on: ubuntu-latest
    environment:
      name: tfstate
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # 2.0.3
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@22b4647f1263865cda4473831640e71d349db2cd # 1.3.2
        with:
          terragrunt_version: 0.51.0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: plan
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_USE_OIDC: "true"
        run: |
          set -e
          export ARM_OIDC_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN
          export ARM_OIDC_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL
          sh scripts/terragrunt-init.sh
          terragrunt plan -no-color -out tfplan | tee tfplan.txt
          terraform show -json tfplan > /dev/null
      - name: Azure login
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302 #v2.2.0
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: Upload plan file
        run: |
          az storage blob upload -f tfplan --account-name tfmod1espoolstatestorage --container-name azure-verified-tfmod-pull-request-plans --name telemetry/tfplan_${{ github.event.number }} --tier Cool --no-progress --overwrite --auth-mode login
          az storage blob upload -f tfplan.txt --account-name tfmod1espoolstatestorage --container-name azure-verified-tfmod-pull-request-plans --name telemetry/tfplan_${{ github.event.number }}.txt --tier Cool --no-progress --overwrite --auth-mode login
      - name: Save the PR number in an artifact
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt
      - name: Upload the PR number
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 #3.1.3
        with:
          name: pr_num
          path: ./pr_num.txt